Models/Link.cs
using System.ComponentModel.DataAnnotations;

namespace shorterLink.Models
{
    public class Link
    {
        [Display(Name="Your link")]
        [RegularExpression("^http(s)?://([\\w-]+.)+[\\w-]+(/[\\w- ./?%&=])?$")]
        public string YourLink { get; set; }

        [Display(Name="Shortcut")]
        public string Shortcut {get; set; }
    }
}

Controllers/ClickController.cs
using System.Collections.Generic;
using HashidsNet;
using Microsoft.AspNetCore.Mvc;
using shorterLink.Interfaces;
using shorterLink.Models;
using System.Linq;

namespace shorterLink.Controllers
{
    public class ClickController : Controller
    {
        private ILinksRepository _repository;

        public ClickController(ILinksRepository linksRepository)
        {
            _repository = linksRepository;
        }

        [HttpGet]
        [Route("/{id}")]
        public IActionResult Index(string id)
        {
            var link = _repository.GetLinkByShortcut(id);
            if (link == null)
            {
                var links = _repository.GetLinks();
                ViewBag.Message = "Link not found. Add it if you like.";
                return View("../Link/Index", links);
            }
            else
            {
                return Redirect(link.YourLink);
            }
        }
    }
}

Controllers/LinkController.cs
using System.Collections.Generic;
using HashidsNet;
using Microsoft.AspNetCore.Mvc;
using shorterLink.Interfaces;
using shorterLink.Models;
using System.Linq;

namespace shorterLink.Controllers
{
    public class LinkController : Controller
    {
        private ILinksRepository _repository;

        public LinkController(ILinksRepository linksRepository)
        {
            _repository = linksRepository;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var links = _repository.GetLinks();
            return View(links);
        }

        [HttpPost]
        public IActionResult Create(Link link)
        {
            if (ModelState.IsValid)
            {
                link.Shortcut = ShortenLink(link);
                _repository.AddLink(link);
            }
            else
            {
                ViewBag.Message = "This is not valid url. You have to start with http:// or https://";
            }
            var links = _repository.GetLinks();
            return View("Index", links);
        }

        [HttpGet]
        public IActionResult Delete(Link link)
        {
            _repository.Delete(link);
            return Redirect("Index");
        }

        private string ShortenLink(Link link)
        {
            var charArray = link.YourLink.ToCharArray();
            var intArray = new int[charArray.Length];

            for (var i = 0; i < charArray.Length; i++)
            {
                intArray[i] = charArray[i];
            }

            var hashids = new Hashids("this is my salt", 8);
            var result = hashids.Encode(intArray.Sum());
            return result;
        }
    }
}

Views/Link/Index.cshtml
@model List<shorterLink.Models.Link>
    <div>
    @using (Html.BeginForm("Create", "Link", FormMethod.Post))
    {
        @if(ViewBag.Message != null){
            <h1>@ViewBag.Message</h1>
        }
        <input type="text" name="YourLink" placeholder="Your Link"/> <br/>
        <button type="submit">Add</button>
    }
    </div>
    <div>
     <table>
         @foreach(var item in Model) {
             <tr>
                 <td><strong>@Html.DisplayNameFor(model => item.YourLink):</strong></td>
                 <td>@Html.DisplayFor(model => item.YourLink),</td>
                 <td><strong>@Html.DisplayNameFor(model => item.Shortcut):</strong></td>
                 <td><a target="_blank" href="/@item.Shortcut">@Html.DisplayFor(model => item.Shortcut)</a>,</td>
                 <td>@Html.ActionLink("Delete", "Delete", "Link", item)</td>
             </tr>
         }
     </table>
    </div>  